// Auth Related Actions
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

// General ( messages, popups) related actions

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';
export const TOAST_MESSAGE = 'TOAST_MESSAGE';
export const TOGGLE_SIDEBAR_CLASS = 'TOGGLE_SIDEBAR_CLASS';
export const START_BUTTON_LOADING = 'START_BUTTON_LOADING'
export const STOP_BUTTON_LOADING = 'STOP_BUTTON_LOADING'
export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'

// Messages Actions

export const GET_MESSAGES = 'GET_MESSAGES';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const START_MESSAGES_LOADING = 'START_MESSAGES_LOADING';
export const STOP_MESSAGES_LOADING = 'STOP_MESSAGES_LOADING';
export const UPDATE_ACTIVE_USERS = 'UPDATE_ACTIVE_USERS';
export const UPDATE_JOINED_USERS = 'UPDATE_JOINED_USERS';
export const UPDATE_LEAVING_USERS = 'UPDATE_LEAVING_USERS';
export const UPDATE_TYPING_USER = 'UPDATE_TYPING_USER';

// Rooms Actions

export const GET_ROOMS = 'GET_ROOMS'
export const GET_ROOM_MEMBERS = 'GET_ROOM_MEMBERS'
export const START_ROOM_MEMBERS_LOADING = 'START_ROOM_MEMBERS_LOADING'
export const STOP_ROOM_MEMBERS_LOADING = 'STOP_ROOM_MEMBERS_LOADING'
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS'
export const ADD_ROOM_FAILS = 'ADD_ROOM_FAILS'
export const GET_ROOM = 'GET_ROOM'
export const SINGLE_ROOM_LOADING_STOP = 'SINGLE_ROOM_LOADING_STOP'
export const SINGLE_ROOM_LOADING_START = 'SINGLE_ROOM_LOADING_START'
export const ROOMS_LOADING_STOP = 'ROOMS_LOADING_STOP'
export const ROOMS_LOADING_START = 'ROOMS_LOADING_START'
//  Users Actions

export const GET_USERS = 'GET_USERS'
export const GET_ROOM_USERS = 'GET_ROOM_USERS'
export const RESET_ROOM_USERS = 'RESET_ROOM_USERS'
